// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfnflwxnjnnjxovkvamx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmbmZsd3huam5uanhvdmt2YW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDY1NTMsImV4cCI6MjA2ODM4MjU1M30.N50QrLHts_MVEA8GI1-qhS3X-UG9m3Uy8KM41Zc3jFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});